import type {NextPage} from 'next'
import Head from 'next/head'
import Hero from "../components/Hero";
import WhatDoIDo from "../components/WhatDoIDo";
import {useColorMode} from "@chakra-ui/react";
import MyGitHub from "../components/MyGitHub";
import Navbar from "../components/Navbar";

const Home: NextPage = () => {
    const {colorMode} = useColorMode()
    const theme = colorMode === "light" ? '' : 'tokyonight';
    return (
        <>
            <Head>
                <title>rique_dev</title>
                <meta name="description" content="Generated by create next app"/>
            </Head>
            <Navbar/>
            <Hero/>
            <WhatDoIDo/>
            <MyGitHub/>
        </>
    )
}

export default Home
