import type {NextPage} from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Hero from "../components/Hero";
import Script from "next/script";
import WhatDoIDo from "../components/WhatDoIDo";

const Home: NextPage = () => {
    return (
        <>
            <Script data-name="BMC-Widget" data-cfasync="false"
                    src="https://cdnjs.buymeacoffee.com/1.0.0/widget.prod.min.js" data-id="riquedevbr"
                    data-description="Support me on Buy me a coffee!" data-message="" data-color="var(--chakra-colors-purple-400)"//"#FFDD00"
                    strategy="beforeInteractive"
                    data-position="Right" data-x_margin="18" data-y_margin="18"/>
            <div className={styles.container}>
                <Head>
                    <title>rique_dev</title>
                    <meta name="description" content="Generated by create next app"/>
                </Head>
                <Hero/>
                <WhatDoIDo/>
            </div>
        </>
    )
}

export default Home
